name: Publish Python Package

on:
  push:
    branches: 
      - main  # Триггер только для ветки main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Установка версии Python
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__  # Используйте секреты для TWINE_USERNAME
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}  # Токен PyPI
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
