name: Publish to PyPI

on:
  push:
    branches:
      - main  # Здесь указывайте только ветку main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12  # Здесь указывайте версию Python

    - name: Install dependencies
      run: pip install python-dotenv setuptools  # Или используйте инструкции для установки зависимостей из pyproject.toml

    - name: Build and publish
      run: |
        python setup.py sdist
        pip install twine
        twine upload dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: "${{secrets.PYPI_TOKEN}}"
